language: c

sudo: false
addons:
    apt:
        packages:
            - lib32stdc++6
            - unzip


before_script:
    - SMPACKAGE="$(wget -qO- "http://www.sourcemod.net/downloads-new.php?branch=dev" | grep linux | cut -d "'" -f 2 | sed -n 2p)"
    - wget $SMPACKAGE
    - mkdir sm18 sharedinclude
    - tar xfz $(basename $SMPACKAGE) -C sm18
    - export sm18=$(pwd)/sm18/addons/sourcemod/scripting
    - wget https://raw.githubusercontent.com/Impact123/AutoExecConfig/master/autoexecconfig.inc -P sharedinclude
    - wget https://raw.githubusercontent.com/popoklopsi/MessageBot/master/messagebot.inc -P sharedinclude
    - wget https://bitbucket.org/GoD_Tony/updater/raw/default/include/updater.inc -P sharedinclude
    - wget -O socket.zip "https://forums.alliedmods.net/attachment.php?attachmentid=83286"
    - unzip -p socket.zip addons/sourcemod/scripting/include/socket.inc > sharedinclude/socket.inc


script:
    - $sm18/spcomp -isharedinclude gameserver/calladmin.sp
    - $sm18/spcomp -isharedinclude gameserver/calladmin_steam.sp
    - $sm18/spcomp -isharedinclude gameserver/calladmin_mysql.sp
    - $sm18/spcomp -isharedinclude gameserver/calladmin_ts3.sp
    - $sm18/spcomp -isharedinclude gameserver/calladmin_test.sp
    - $sm18/spcomp -isharedinclude gameserver/calladmin_usermanager.sp
