language: c

sudo: false
addons:
    apt:
        packages:
            - lib32stdc++6
            - unzip


env:
    - SMBRANCH=1.7
    - SMBRANCH=1.8


before_script:
    - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMBRANCH}"
    - wget "$SMPACKAGE" -O latest.tar.gz
    - mkdir $SMBRANCH
    - tar xfz latest.tar.gz -C $SMBRANCH
    - export SMPATH=$(pwd)/$SMBRANCH/addons/sourcemod/scripting


script:
    - $SMPATH/spcomp gameserver/calladmin.sp
    - $SMPATH/spcomp gameserver/calladmin_steam.sp
    - $SMPATH/spcomp gameserver/calladmin_mysql.sp
    - $SMPATH/spcomp gameserver/calladmin_ts3.sp
    - $SMPATH/spcomp gameserver/calladmin_test.sp
    - $SMPATH/spcomp gameserver/calladmin_usermanager.sp
