language: c

sudo: false
addons:
    apt:
        packages:
            - lib32stdc++6
            - unzip


env:
    - SMBRANCH=1.7
    - SMBRANCH=1.8


before_script:
    - SMPACKAGE="http://www.sourcemod.net/smdrop/${SMBRANCH}/$(wget -qO- "http://www.sourcemod.net/smdrop/${SMBRANCH}/" | grep linux*.tar.gz | cut -d "\"" -f 2 | tail -n 1)"
    - wget $SMPACKAGE
    - mkdir $SMBRANCH
    - tar xfz $(basename $SMPACKAGE) -C $SMBRANCH
    - export SMBRANCH=$(pwd)/$SMBRANCH/addons/sourcemod/scripting


script:
    - $SMBRANCH/spcomp -isharedinclude gameserver/calladmin.sp
    - $SMBRANCH/spcomp -isharedinclude gameserver/calladmin_steam.sp
    - $SMBRANCH/spcomp -isharedinclude gameserver/calladmin_mysql.sp
    - $SMBRANCH/spcomp -isharedinclude gameserver/calladmin_ts3.sp
    - $SMBRANCH/spcomp -isharedinclude gameserver/calladmin_test.sp
    - $SMBRANCH/spcomp -isharedinclude gameserver/calladmin_usermanager.sp
