language: c

sudo: false
addons:
    apt:
        packages:
            - lib32stdc++6
            - zip
            - unzip

env:
    matrix:
        - SMBRANCH=1.9
        - SMBRANCH=1.10
    - secure: 
        global:
            # FTP_USER
            secure: uGG2kUnnc2L7gp8YOU9DzM2ySqA0kRJ8+ZZt4owZxx2rd5w6AjBtN23aVHchAipHnPKvWQwxCFrmVWd/bkFtYgVYRWdOO5bTCcW7yvhwMnizPH/VsaPoT3n79Z8snZOiChhOJpjumymlErsJ4Gi0X9rNBqjze8dW1MgnT3XPwEE=
            # FTP_PASSWORD
            secure: ooXHvANmH7ycHXOIQZchGBLddvSmHFkF2OQR8DWI3FdiwqZuOAp6wPpDqzRGpnAYnjVKw8f68LJblzxAIjETjB53mcCGpvh8yAQNbw33BNNcTGYS0hhKFwXdTHhPoX8aWfVAZCQodAbPQ5bz70VtOsmFwjJze/pPBUKla5SOoK4=
before_script:
    - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMBRANCH}"
    - wget "$SMPACKAGE" -O latest.tar.gz
    - mkdir $SMBRANCH
    - tar xfz latest.tar.gz -C $SMBRANCH
    - export SMPATH=$(pwd)/$SMBRANCH/addons/sourcemod/scripting
    - mkdir -p plugins/disabled scripting/include scripting/include/system2/ translations
    - cp gameserver/calladmin*.sp scripting/
    - cp gameserver/include/*.inc scripting/include/
    - cp gameserver/include/system2/*.inc scripting/include/system2/
    - cp gameserver/*.phrases.txt translations/

script:
    - $SMPATH/spcomp gameserver/calladmin.sp
    - $SMPATH/spcomp gameserver/calladmin_steam.sp
    - $SMPATH/spcomp gameserver/calladmin_mysql.sp
    - $SMPATH/spcomp gameserver/calladmin_ts3.sp
    - $SMPATH/spcomp gameserver/calladmin_test.sp
    - $SMPATH/spcomp gameserver/calladmin_usermanager.sp
    - mv calladmin*.smx plugins/
    - mv plugins/calladmin_test.smx plugins/disabled/
    - zip -q -9 -r calladmin_gameserver.zip plugins/ scripting/ translations/
    - zip -q -9 -r calladmin_web.zip web/

deploy:
    - provider: releases
        skip_cleanup: true
        api_key:
            secure: aluHVTVa3DatUISjPUUck1YNlOVqNiZI7F4Lk0DcTpGuSs38UtZYbxXXHibrq004LP/R1GvMxFZx0rkYDKJJyJw0HpoQlodsgm5T3g5OJAcHfrD8WcR0R5T5GBUBaTZ6copr5175TDhMcGTHTA66rFDmch7Sh1m86IVhwhlJbag=
        file:
            - calladmin_gameserver.zip
            - calladmin_web.zip
        on:
            condition: "$SMBRANCH = 1.9"
            tags: true
            repo: Impact123/CallAdmin
        branches:
            only:
                - master
                - development
    - provider: script
        script:
            - bash deploy.sh
        on:
            condition: "$SMBRANCH = 1.9"
            repo: Impact123/CallAdmin
            branch: development
